[0m12:59:08.480159 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B47C60BC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B49A88380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B49A8A120>]}


============================== 12:59:08.506133 | 37f5e314-aa35-426a-8fc2-f6a6ae598b71 ==============================
[0m12:59:08.506133 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:59:08.509775 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\lokesh.2.yadav\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:59:32.946805 [debug] [MainThread]: Starter project path: C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\include\starter_project
[0m12:59:32.961996 [info ] [MainThread]: 
Your new dbt project "dbt_demo" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:59:32.969432 [info ] [MainThread]: Setting up your profile.
[0m13:14:53.963387 [error] [MainThread]: Encountered an error:

[0m13:14:53.970270 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m13:14:53.973272 [debug] [MainThread]: Command `dbt init` failed at 13:14:53.973272 after 945.99 seconds
[0m13:14:53.973272 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B49AE7140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B4C368650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021B4B159D90>]}
[0m13:14:53.974272 [debug] [MainThread]: Flushing usage events
[0m13:14:54.968758 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:16:13.230438 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002140A934380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002140B0991C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002140AF30EC0>]}


============================== 13:16:13.237571 | b25f88e8-0b7a-47b2-a0ef-32a5337cff33 ==============================
[0m13:16:13.237571 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:16:13.239059 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lokesh.2.yadav\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:16:19.668622 [debug] [MainThread]: Starter project path: C:\Users\lokesh.2.yadav\course\venv\Lib\site-packages\dbt\include\starter_project
[0m13:16:19.722013 [info ] [MainThread]: 
Your new dbt project "dbt_demo" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:16:19.723032 [info ] [MainThread]: Setting up your profile.
[0m13:19:30.440336 [info ] [MainThread]: Profile dbt_demo written to C:\Users\lokesh.2.yadav\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:19:30.445942 [debug] [MainThread]: Command `dbt init` succeeded at 13:19:30.445942 after 197.73 seconds
[0m13:19:30.446958 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002140B3857F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002140B3860F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002140B0991C0>]}
[0m13:19:30.448984 [debug] [MainThread]: Flushing usage events
[0m13:19:30.936515 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:23:02.248612 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243CDEC3EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243CDF49160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243CDEEF9E0>]}


============================== 13:23:02.259997 | 2810bd67-b302-4c80-8d78-b2020d25372e ==============================
[0m13:23:02.259997 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:23:02.262871 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\lokesh.2.yadav\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:23:02.301145 [info ] [MainThread]: dbt version: 1.9.1
[0m13:23:02.301145 [info ] [MainThread]: python version: 3.12.8
[0m13:23:02.302145 [info ] [MainThread]: python path: C:\Users\lokesh.2.yadav\course\venv\Scripts\python.exe
[0m13:23:02.303146 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m13:23:02.658641 [info ] [MainThread]: Using profiles dir at C:\Users\lokesh.2.yadav\.dbt
[0m13:23:02.659683 [info ] [MainThread]: Using profiles.yml file at C:\Users\lokesh.2.yadav\.dbt\profiles.yml
[0m13:23:02.660718 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\lokesh.2.yadav\course\dbt_project.yml
[0m13:23:02.661683 [info ] [MainThread]: adapter type: snowflake
[0m13:23:02.662708 [info ] [MainThread]: adapter version: 1.9.0
[0m13:23:02.662708 [info ] [MainThread]: Configuration:
[0m13:23:02.663682 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m13:23:02.663682 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:23:02.663682 [info ] [MainThread]: Required dependencies:
[0m13:23:02.664791 [debug] [MainThread]: Executing "git --help"
[0m13:23:02.684236 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m13:23:02.685747 [info ] [MainThread]: Connection:
[0m13:23:02.689873 [info ] [MainThread]:   account: YNFZCCG-AM86726
[0m13:23:02.691238 [info ] [MainThread]:   user: dbt
[0m13:23:02.692255 [info ] [MainThread]:   database: raw
[0m13:23:02.694319 [info ] [MainThread]:   warehouse: COMPUTE_WH
[0m13:23:02.694319 [info ] [MainThread]:   role: transform
[0m13:23:02.695843 [info ] [MainThread]:   schema: airbin
[0m13:23:02.695843 [info ] [MainThread]:   authenticator: None
[0m13:23:02.696958 [info ] [MainThread]:   oauth_client_id: None
[0m13:23:02.697967 [info ] [MainThread]:   query_tag: None
[0m13:23:02.698565 [info ] [MainThread]:   client_session_keep_alive: False
[0m13:23:02.698565 [info ] [MainThread]:   host: None
[0m13:23:02.699573 [info ] [MainThread]:   port: None
[0m13:23:02.700575 [info ] [MainThread]:   proxy_host: None
[0m13:23:02.700575 [info ] [MainThread]:   proxy_port: None
[0m13:23:02.701574 [info ] [MainThread]:   protocol: None
[0m13:23:02.702575 [info ] [MainThread]:   connect_retries: 1
[0m13:23:02.703573 [info ] [MainThread]:   connect_timeout: None
[0m13:23:02.703573 [info ] [MainThread]:   retry_on_database_errors: False
[0m13:23:02.706313 [info ] [MainThread]:   retry_all: False
[0m13:23:02.708172 [info ] [MainThread]:   insecure_mode: False
[0m13:23:02.709645 [info ] [MainThread]:   reuse_connections: True
[0m13:23:02.711836 [info ] [MainThread]: Registered adapter: snowflake=1.9.0
[0m13:23:03.090868 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m13:23:03.324903 [debug] [MainThread]: Using snowflake connection "debug"
[0m13:23:03.324903 [debug] [MainThread]: On debug: select 1 as id
[0m13:23:03.324903 [debug] [MainThread]: Opening a new connection, currently in state init
[0m13:23:05.435756 [debug] [MainThread]: SQL status: SUCCESS 1 in 2.110 seconds
[0m13:23:05.438879 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m13:23:05.441656 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:23:05.443971 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\lokesh.2.yadav\course\dbt_project.yml> not found

[0m13:23:05.447061 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m13:23:05.453264 [debug] [MainThread]: Command `dbt debug` failed at 13:23:05.452268 after 3.55 seconds
[0m13:23:05.454259 [debug] [MainThread]: Connection 'debug' was left open.
[0m13:23:05.454259 [debug] [MainThread]: On debug: Close
[0m13:23:05.588421 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243CDC7D7C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243CFF788C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243CE3DF9E0>]}
[0m13:23:05.590443 [debug] [MainThread]: Flushing usage events
[0m13:23:05.989986 [debug] [MainThread]: An error was encountered while trying to flush usage events
